name: Markdown to PDF
on:
  push:
    branches:
      - main
    paths:
      - 'markdown/**.md'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: markdown
          output_dir: pdfs
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: markdown
          path: pdfs
