name: Build Markdown Documents

on:
  push:
    branches:
      - main
#    paths:
#      - 'markdown/**.md'
jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Compile Markdown
        run: |
          echo "Compiling markdown files."
          sudo bash scripts/compile_md.bash
          ls -l pdfs

      - name: Commit markdown files
        run: |
          current_date=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
          commit_hash=$(git rev-parse HEAD)
          COMMIT_MESSAGE="Markdown compiled at ${current_date} commit hash ${commit_hash}."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull  
          git add .
          git commit -m "${COMMIT_MESSAGE}"
          git push https://${COMMIT_KEY}@github.com/jakvitov/statnice_otazky.git