name: Build LaTeX Documents

on:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Compile latex
        run: |
          echo "Compiling latex files."
          sudo bash scripts/compile_tex.bash

      - name: Commit latex files
        run: |
          current_date=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
          commit_hash=$(git rev-parse HEAD)
          COMMIT_MESSAGE="LaTeX compiled at ${current_date} commit hash ${commit_hash}."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "${COMMIT_MESSAGE}"
          git push